[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
cache = true
cache_path = 'cache'
broadcast = 'broadcast'


[rpc_endpoints]
katana = "https://rpc.katana.network"
tatara = "https://rpc.tatara.katanarpc.com"
bokuto = "https://rpc-bokuto.katanarpc.com"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
